apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-deployment
  namespace: api
  labels:
    deploy: user-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - image: "registryipy0113.azurecr.io/user-java:1.0"
        imagePullPolicy: Always
        name: user-java
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
        envFrom:
          - secretRef:
              name: sql
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: user-java
  ports:
    - protocol: TCP
      name: user-java-http
      port: 80
      targetPort: 80
