apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydrive-user-deployment
  namespace: api
  labels:
    deploy: mydrive-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydrive-user
  template:
    metadata:
      labels:
        app: mydrive-user
    spec:
      containers:
      - image: "registryipy0113.azurecr.io/userprofile:1.0"
        imagePullPolicy: Always
        name: mydrive-user
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
        envFrom:
          - secretRef:
              name: sql
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: mydrive-user
  ports:
    - protocol: TCP
      name: mydrive-user-http
      port: 80
      targetPort: 80
